devices:
- connection:
    snmp:
      community: public
      port: 161
      retry: 3
      timeout: 10
    ssh:
      password: admin123
      port: 22
      retry: 3
      timeout: 10
      username: admin
  ip: 192.168.1.100
  name: Router_A
- connection:
    snmp:
      community: awatch
      port: 161
      retry: 0
      timeout: 2
  ip: 192.168.2.1
  name: Fortinet_60
- connection:
    snmp:
      community: awatch
      port: 161
      retry: 0
      timeout: 2
    ssh:
      password: admin
      port: 22
      retry: 0
      timeout: 2
      username: admin
  ip: 192.168.2.11
  name: AP-205
tasks:
- alias: fgProcessorUsage_per
  enabled: true
  labels:
  - fgProcessorUsage.1
  - fgProcessorUsage.2
  - fgProcessorUsage.3
  - fgProcessorUsage.4
  oid: 1.3.6.1.4.1.12356.101.4.4.2.1.2
  protocol: snmp
  schedule:
    frequency: 0
    mode: interval
    seconds: 5
  storage: sqlite
  targets:
  - Fortinet_60
  type: snmpwalk
- alias: run_router_a_tech_support
  command:
  - show tech-support
  enabled: false
  protocol: ssh
  schedule:
    frequency: 0
    mode: delay
    seconds: 120
  storage: file
  targets:
  - Router_A
- alias: get_router_a_version
  command:
  - show version
  enabled: false
  protocol: ssh
  schedule:
    frequency: 1
  storage: sqlite
  targets:
  - Router_A
- alias: clear_router_a_counters
  command:
  - clear counters
  enabled: false
  protocol: ssh
  schedule:
    frequency: 1
  storage: null
  targets:
  - Router_A
- alias: check_router_a_datapath
  command:
  - show datapath network ingress
  enabled: false
  labels:
  - queue_empty_count
  - queue_empty_recovery
  parse:
    regex: \|\s*G\s*\|\s*\[000\]\s*\|\s*Current Entries\s+(\d+)
  protocol: ssh
  schedule:
    frequency: 0
    mode: delay
    seconds: 60
  storage: sqlite
  targets:
  - Router_A
- alias: fgSysSesCount
  enabled: true
  labels:
  - fgSysSesCount
  oid: 1.3.6.1.4.1.12356.101.4.1.8.0
  protocol: snmp
  schedule:
    frequency: 0
    mode: interval
    seconds: 5
  storage: file
  targets:
  - Fortinet_60
  type: snmpget
- alias: fgSysMemUsage
  enabled: true
  labels:
  - fgSysMemUsage
  oid: 1.3.6.1.4.1.12356.101.4.1.4.0
  protocol: snmp
  schedule:
    frequency: 0
    mode: interval
    seconds: 5
  storage: sqlite
  targets:
  - Fortinet_60
  type: snmpget
- alias: fgSysUpTime
  enabled: true
  labels:
  - SysUpTime
  oid: 1.3.6.1.2.1.1.3.0
  protocol: snmp
  schedule:
    frequency: 0
    mode: interval
    seconds: 5
  storage: sqlite
  targets:
  - Fortinet_60
  - AP-205
  type: snmpget
